### ISSUE TITLE
firebase reservation list overwrite error #6

### ISSUE THREAD

**Issue by 3uhyeon** [kookmin-sw/capstone-2024-26#6]
파이어베이스에 같은 uid로 다른 날짜로 예약할시에 마지막 예약한 날짜로 데이터가 덮어쓰기되는 문제

**Comment by Uiseokjung** [comment]
덮어쓰기 문제를 현재 사용자가 예약한 문서 개수를 통해 이메일 옆에 번호로 나타내는 형식으로 고유한 문서로 만듦
